name = "ZluskeN Whistle"
prefix = "zsn"
modname = "zsn_visselpipa"
version = "0.0.0"
author = "ZluskeN"
files = [
    "meta.cpp",
    "mod.cpp",
    "whistleicon.paa",
]
key_name = "zsn"
reuse_private_key = true
authority = "zsn"
sig_version = 3
